version: 2
updates:
  # GitHub Actions updater
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    reviewers:
      - "sachinsaurav302"

  # NPM package updater
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "sachinsaurav302"
