version: 2
updates:
  # 1) GitHub Actions update (workflows me use hone wale actions)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "sachinsaurav302"

  # 2) NPM dependencies (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "sachinsaurav302"
