name: Terraform check

# Triggering the workflow on a workflow_call event
on:
  
  push:
    branches:
      - main

jobs:
# Job to Validate Terraform Configuration
  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      # Check out the project repository          
      - name: Checkout Project
        uses: actions/checkout@v4